language: python
env:
  - TEST_PROFILE="test.autotools.yaml"
  - TEST_PROFILE="test.boost.yaml"
  - TEST_PROFILE="test.clawpack.gitsubmodules.yaml"
  - TEST_PROFILE="test.cmake.yaml"
  - TEST_PROFILE="test.host-scipy.yaml"
  - TEST_PROFILE="test.matplotlib.yaml"
  - TEST_PROFILE="test.packages1.yaml"
  - TEST_PROFILE="test.packages2.yaml"
  - TEST_PROFILE="test.packages3.yaml"
  - TEST_PROFILE="test.packages4.yaml"
  - TEST_PROFILE="test.netcdf4.yaml"
  - TEST_PROFILE="test.vxl.yaml"
  - TEST_PROFILE="test.dolfin.yaml"
python:
  - 2.7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install gfortran pv
  - if [[ "${TEST_PROFILE}" == "test.packages1.yaml" ]]; then
      sudo apt-get install liblapack-dev;
    fi
  - if [[ "${TEST_PROFILE}" == "test.packages2.yaml" ]]; then
      sudo apt-get install mpich2 liblapack-dev;
    fi
  - if [[ "${TEST_PROFILE}" == "test.packages3.yaml" ]]; then
      sudo apt-get install mpich2 liblapack-dev;
    fi
  - if [[ "${TEST_PROFILE}" == "test.cmake.yaml" ]]; then
       sudo apt-get install mpich2;
     fi
  - if [[ "${TEST_PROFILE}" == "test.boost.yaml" ]]; then
      sudo apt-get install mpich2;
    fi
  - if [[ "${TEST_PROFILE}" == "test.clawpack.gitsubmodules.yaml" ]]; then
      sudo apt-get install liblapack-dev;
    fi
  - if [[ "${TEST_PROFILE}" == "test.netcdf4.yaml" ]]; then
      sudo apt-get install mpich2;
    fi
  - if [[ "${TEST_PROFILE}" == "test.host-scipy.yaml" ]]; then
      sudo apt-get install python-scipy;
    fi
  - if [[ "${TEST_PROFILE}" == "test.dolfin.yaml" ]]; then
      sudo apt-get install cmake libopenmpi-dev python-dev libblas-dev liblapack-dev swig wget;
    fi
install:
  - git clone https://github.com/hashdist/hashdist
  - export PATH=`pwd`/hashdist/bin:$PATH
script:
  - cp tests/$TEST_PROFILE $TEST_PROFILE
  - set -o pipefail
  - hit build $TEST_PROFILE -v 2>&1 | pv -i 15 -n | cat > log.txt
  - tail -n 60 log.txt
verify:
  - if [[ "${TEST_PROFILE}" == "test.matplotlib.yaml" ]]; then
      ./test.matplotlib/bin/python -c "from mpl_toolkits.mplot3d import Axes3D"
    fi
  - if [[ "${TEST_PROFILE}" == "test.dolfin.yaml" ]]; then
      ./test.dolfin/bin/python -c "from dolfin import *"
    fi
notifications:
  email: false
